name: Secret Scan

on:
  push:
  pull_request:

jobs:
  secret-scan:
    uses: SchneiderSaddlery/org-reusable-workflows/.github/workflows/secret-scan.yml@main
    secrets:
      gitleaks_license: ${{ secrets.GITLEAKS_LICENSE }}
